### ISSUE TITLE
Username/Password expostos

### ISSUE THREAD

**Issue by brazilianbytes** [micaelparadox/wormainsofdoom#4]
Olá

Sou da Doutor ao Vivo e navegando no seu repo, percebi que seu usuário e senha do gmail estão expostos. Melhor criar como segredo dentro do Heroku.

Grande abraço!

**Comment by brazilianbytes** [comment]
@micaelparadox

**Comment by micaelparadox** [comment]
Origado, essa aplicação é usada apenas para algumas pessoas só nao tem problemas mas eu agradeço.

**Comment by micaelparadox** [comment]
thanks <3
